run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Synchronize current path when splitting
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Fix neovim bg color
set-option -ga terminal-overrides ",xterm-256color:Tc"
